/**
 * The doom-emacs theme library ported from this machine's install
 * (~/.config/emacs/.local/straight/build-30.2/doom-themes): each theme's
 * bg / bg-alt / base-ramp / fg / highlight colors mapped onto the token
 * layer, with the theme's `highlight` (or its most vivid accent) as the
 * signature color for the brand and the active mode-line fill. Generated
 * by extraction — regenerate with the doom-palettes extractor rather than
 * hand-editing individual palettes.
 */
import type { ThemeDefinition } from '@deepseek-ai/dsh-client-ui-theme/client'

type DoomPalette = Record<string, string>

function doomTheme(id: string, dark: boolean, palette: DoomPalette): ThemeDefinition {
  return { id, colorScheme: dark ? 'dark' : 'light', tokens: palette }
}

export const DOOM_THEMES: readonly ThemeDefinition[] = [
  doomTheme('doom-1337', true, {
    '--dsw-alias-bg-base': '#191919',
    '--dsw-alias-bg-layer-1': '#252526',
    '--dsw-alias-bg-layer-2': '#4b474c',
    '--dsw-alias-bg-overlay': '#252526',
    '--dsw-alias-label-primary': '#d4d4d4',
    '--dsw-alias-label-secondary': '#AEAFAD',
    '--dsw-alias-border-l1': '#252526',
    '--dsw-alias-border-l2': '#121212',
    '--dsw-alias-border-l3': '#1C1C1C',
    '--dsw-specific-sidebar-fill': '#252526',
    '--dsw-alias-brand-primary': '#8CDAFF',
    '--dsw-alias-mode-line-active': '#8CDAFF',
  }),
  doomTheme('doom-Iosvkem', true, {
    '--dsw-alias-bg-base': '#1b1d1e',
    '--dsw-alias-bg-layer-1': '#262829',
    '--dsw-alias-bg-layer-2': '#505050',
    '--dsw-alias-bg-overlay': '#262829',
    '--dsw-alias-label-primary': '#dddddd',
    '--dsw-alias-label-secondary': '#5B6268',
    '--dsw-alias-border-l1': '#262829',
    '--dsw-alias-border-l2': '#303030',
    '--dsw-alias-border-l3': '#202020',
    '--dsw-specific-sidebar-fill': '#262829',
    '--dsw-alias-brand-primary': '#6c9ef8',
    '--dsw-alias-mode-line-active': '#6c9ef8',
  }),
  doomTheme('doom-acario-dark', true, {
    '--dsw-alias-bg-base': '#0D0E16',
    '--dsw-alias-bg-layer-1': '#040408',
    '--dsw-alias-bg-layer-2': '#585C6C',
    '--dsw-alias-bg-overlay': '#040408',
    '--dsw-alias-label-primary': '#CEDBE5',
    '--dsw-alias-label-secondary': '#E5F4FF',
    '--dsw-alias-border-l1': '#040408',
    '--dsw-alias-border-l2': '#1E1E33',
    '--dsw-alias-border-l3': '#121212',
    '--dsw-specific-sidebar-fill': '#040408',
    '--dsw-alias-brand-primary': '#3679D8',
    '--dsw-alias-mode-line-active': '#3679D8',
  }),
  doomTheme('doom-acario-light', false, {
    '--dsw-alias-bg-base': '#F5F5F9',
    '--dsw-alias-bg-layer-1': '#E9E9F2',
    '--dsw-alias-bg-layer-2': '#585C6C',
    '--dsw-alias-bg-overlay': '#E9E9F2',
    '--dsw-alias-label-primary': '#0F1019',
    '--dsw-alias-label-secondary': '#0D0E16',
    '--dsw-alias-border-l1': '#E9E9F2',
    '--dsw-alias-border-l2': '#C0CCD0',
    '--dsw-alias-border-l3': '#D0D0E3',
    '--dsw-specific-sidebar-fill': '#E9E9F2',
    '--dsw-alias-brand-primary': '#1F55A0',
    '--dsw-alias-mode-line-active': '#1F55A0',
  }),
  doomTheme('doom-badger', true, {
    '--dsw-alias-bg-base': '#171717',
    '--dsw-alias-bg-layer-1': '#2f2f2f',
    '--dsw-alias-bg-layer-2': '#433F4f',
    '--dsw-alias-bg-overlay': '#2f2f2f',
    '--dsw-alias-label-primary': '#F6F3E8',
    '--dsw-alias-label-secondary': '#FBF9F3',
    '--dsw-alias-border-l1': '#2f2f2f',
    '--dsw-alias-border-l2': '#202328',
    '--dsw-alias-border-l3': '#1c1f24',
    '--dsw-specific-sidebar-fill': '#2f2f2f',
    '--dsw-alias-brand-primary': '#8AC6F2',
    '--dsw-alias-mode-line-active': '#8AC6F2',
  }),
  doomTheme('doom-bluloco-dark', true, {
    '--dsw-alias-bg-base': '#282c34',
    '--dsw-alias-bg-layer-1': '#23252A',
    '--dsw-alias-bg-layer-2': '#595e68',
    '--dsw-alias-bg-overlay': '#23252A',
    '--dsw-alias-label-primary': '#abb2bf',
    '--dsw-alias-label-secondary': '#7a808b',
    '--dsw-alias-border-l1': '#23252A',
    '--dsw-alias-border-l2': '#404450',
    '--dsw-alias-border-l3': '#2E333C',
    '--dsw-specific-sidebar-fill': '#23252A',
    '--dsw-alias-brand-primary': '#10b1fe',
    '--dsw-alias-mode-line-active': '#10b1fe',
  }),
  doomTheme('doom-bluloco-light', false, {
    '--dsw-alias-bg-base': '#f9f9f9',
    '--dsw-alias-bg-layer-1': '#e7e7e7',
    '--dsw-alias-bg-layer-2': '#9ca0a4',
    '--dsw-alias-bg-overlay': '#e7e7e7',
    '--dsw-alias-label-primary': '#383a42',
    '--dsw-alias-label-secondary': '#c6c7c7',
    '--dsw-alias-border-l1': '#e7e7e7',
    '--dsw-alias-border-l2': '#dfdfdf',
    '--dsw-alias-border-l3': '#e7e7e7',
    '--dsw-specific-sidebar-fill': '#e7e7e7',
    '--dsw-alias-brand-primary': '#0098dd',
    '--dsw-alias-mode-line-active': '#0098dd',
  }),
  doomTheme('doom-challenger-deep', true, {
    '--dsw-alias-bg-base': '#1E1C31',
    '--dsw-alias-bg-layer-1': '#12111E',
    '--dsw-alias-bg-layer-2': '#565575',
    '--dsw-alias-bg-overlay': '#12111E',
    '--dsw-alias-label-primary': '#CBE3E7',
    '--dsw-alias-label-secondary': '#B2B2B2',
    '--dsw-alias-border-l1': '#12111E',
    '--dsw-alias-border-l2': '#3D4551',
    '--dsw-alias-border-l3': '#292F37',
    '--dsw-specific-sidebar-fill': '#12111E',
    '--dsw-alias-brand-primary': '#91DDFF',
    '--dsw-alias-mode-line-active': '#91DDFF',
  }),
  doomTheme('doom-city-lights', true, {
    '--dsw-alias-bg-base': '#1D252C',
    '--dsw-alias-bg-layer-1': '#181E24',
    '--dsw-alias-bg-layer-2': '#384551',
    '--dsw-alias-bg-overlay': '#181E24',
    '--dsw-alias-label-primary': '#A0B3C5',
    '--dsw-alias-label-secondary': '#728CA0',
    '--dsw-alias-border-l1': '#181E24',
    '--dsw-alias-border-l2': '#20282F',
    '--dsw-alias-border-l3': '#171D22',
    '--dsw-specific-sidebar-fill': '#181E24',
    '--dsw-alias-brand-primary': '#5EC4FF',
    '--dsw-alias-mode-line-active': '#5EC4FF',
  }),
  doomTheme('doom-dark+', true, {
    '--dsw-alias-bg-base': '#1e1e1e',
    '--dsw-alias-bg-layer-1': '#252526',
    '--dsw-alias-bg-layer-2': '#4b474c',
    '--dsw-alias-bg-overlay': '#252526',
    '--dsw-alias-label-primary': '#d4d4d4',
    '--dsw-alias-label-secondary': '#AEAFAD',
    '--dsw-alias-border-l1': '#252526',
    '--dsw-alias-border-l2': '#121212',
    '--dsw-alias-border-l3': '#1C1C1C',
    '--dsw-specific-sidebar-fill': '#252526',
    '--dsw-alias-brand-primary': '#339CDB',
    '--dsw-alias-mode-line-active': '#339CDB',
  }),
  doomTheme('doom-dracula', true, {
    '--dsw-alias-bg-base': '#282a36',
    '--dsw-alias-bg-layer-1': '#1E2029',
    '--dsw-alias-bg-layer-2': '#565761',
    '--dsw-alias-bg-overlay': '#1E2029',
    '--dsw-alias-label-primary': '#f8f8f2',
    '--dsw-alias-label-secondary': '#e2e2dc',
    '--dsw-alias-border-l1': '#1E2029',
    '--dsw-alias-border-l2': '#373844',
    '--dsw-alias-border-l3': '#282a36',
    '--dsw-specific-sidebar-fill': '#1E2029',
    '--dsw-alias-brand-primary': '#61bfff',
    '--dsw-alias-mode-line-active': '#61bfff',
  }),
  doomTheme('doom-ephemeral', true, {
    '--dsw-alias-bg-base': '#323f4e',
    '--dsw-alias-bg-layer-1': '#28323e',
    '--dsw-alias-bg-layer-2': '#323f4e',
    '--dsw-alias-bg-overlay': '#28323e',
    '--dsw-alias-label-primary': '#f8f8f2',
    '--dsw-alias-label-secondary': '#fdfdfd',
    '--dsw-alias-border-l1': '#28323e',
    '--dsw-alias-border-l2': '#242d39',
    '--dsw-alias-border-l3': '#1e262d',
    '--dsw-specific-sidebar-fill': '#28323e',
    '--dsw-alias-brand-primary': '#92b6f4',
    '--dsw-alias-mode-line-active': '#92b6f4',
  }),
  doomTheme('doom-fairy-floss', true, {
    '--dsw-alias-bg-base': '#5a5475',
    '--dsw-alias-bg-layer-1': '#343145',
    '--dsw-alias-bg-layer-2': '#A0A0C0',
    '--dsw-alias-bg-overlay': '#343145',
    '--dsw-alias-label-primary': '#F8F8F0',
    '--dsw-alias-label-secondary': '#B5B2Bd',
    '--dsw-alias-border-l1': '#343145',
    '--dsw-alias-border-l2': '#6A6483',
    '--dsw-alias-border-l3': '#514C66',
    '--dsw-specific-sidebar-fill': '#343145',
    '--dsw-alias-brand-primary': '#55b3cc',
    '--dsw-alias-mode-line-active': '#55b3cc',
  }),
  doomTheme('doom-feather-dark', true, {
    '--dsw-alias-bg-base': '#251D2F',
    '--dsw-alias-bg-layer-1': '#1A1521',
    '--dsw-alias-bg-layer-2': '#342942',
    '--dsw-alias-bg-overlay': '#1A1521',
    '--dsw-alias-label-primary': '#c4b8d3',
    '--dsw-alias-label-secondary': '#503F65',
    '--dsw-alias-border-l1': '#1A1521',
    '--dsw-alias-border-l2': '#16121C',
    '--dsw-alias-border-l3': '#130F18',
    '--dsw-specific-sidebar-fill': '#1A1521',
    '--dsw-alias-brand-primary': '#51afef',
    '--dsw-alias-mode-line-active': '#51afef',
  }),
  doomTheme('doom-feather-light', false, {
    '--dsw-alias-bg-base': '#F0EDF4',
    '--dsw-alias-bg-layer-1': '#E8E4EE',
    '--dsw-alias-bg-layer-2': '#B4A5C7',
    '--dsw-alias-bg-overlay': '#E8E4EE',
    '--dsw-alias-label-primary': '#4A3B5E',
    '--dsw-alias-label-secondary': '#9783B1',
    '--dsw-alias-border-l1': '#E8E4EE',
    '--dsw-alias-border-l2': '#D9D2E3',
    '--dsw-alias-border-l3': '#E1DBE9',
    '--dsw-specific-sidebar-fill': '#E8E4EE',
    '--dsw-alias-brand-primary': '#007daf',
    '--dsw-alias-mode-line-active': '#007daf',
  }),
  doomTheme('doom-henna', true, {
    '--dsw-alias-bg-base': '#21272e',
    '--dsw-alias-bg-layer-1': '#1B1F23',
    '--dsw-alias-bg-layer-2': '#282C34',
    '--dsw-alias-bg-overlay': '#1B1F23',
    '--dsw-alias-label-primary': '#f8f8f0',
    '--dsw-alias-label-secondary': '#6B717D',
    '--dsw-alias-border-l1': '#1B1F23',
    '--dsw-alias-border-l2': '#1B1F23',
    '--dsw-alias-border-l3': '#181A1F',
    '--dsw-specific-sidebar-fill': '#1B1F23',
    '--dsw-alias-brand-primary': '#56b5c2',
    '--dsw-alias-mode-line-active': '#56b5c2',
  }),
  doomTheme('doom-homage-black', true, {
    '--dsw-alias-bg-base': '#000000',
    '--dsw-alias-bg-layer-1': '#000000',
    '--dsw-alias-bg-layer-2': '#3f444a',
    '--dsw-alias-bg-overlay': '#000000',
    '--dsw-alias-label-primary': '#bbc2cf',
    '--dsw-alias-label-secondary': '#5B6268',
    '--dsw-alias-border-l1': '#000000',
    '--dsw-alias-border-l2': '#202328',
    '--dsw-alias-border-l3': '#1c1f24',
    '--dsw-specific-sidebar-fill': '#000000',
    '--dsw-alias-brand-primary': '#0170bf',
    '--dsw-alias-mode-line-active': '#0170bf',
  }),
  doomTheme('doom-homage-white', false, {
    '--dsw-alias-bg-base': '#fafafa',
    '--dsw-alias-bg-layer-1': '#f0f0f0',
    '--dsw-alias-bg-layer-2': '#9ca0a4',
    '--dsw-alias-bg-overlay': '#f0f0f0',
    '--dsw-alias-label-primary': '#383a42',
    '--dsw-alias-label-secondary': '#c6c7c7',
    '--dsw-alias-border-l1': '#f0f0f0',
    '--dsw-alias-border-l2': '#dfdfdf',
    '--dsw-alias-border-l3': '#e7e7e7',
    '--dsw-specific-sidebar-fill': '#f0f0f0',
    '--dsw-alias-brand-primary': '#014980',
    '--dsw-alias-mode-line-active': '#014980',
  }),
  doomTheme('doom-horizon', true, {
    '--dsw-alias-bg-base': '#232530',
    '--dsw-alias-bg-layer-1': '#1c1e26',
    '--dsw-alias-bg-layer-2': '#6a6a6a',
    '--dsw-alias-bg-overlay': '#1c1e26',
    '--dsw-alias-label-primary': '#c7c9cb',
    '--dsw-alias-label-secondary': '#fdf0ed',
    '--dsw-alias-border-l1': '#1c1e26',
    '--dsw-alias-border-l2': '#1d1f27',
    '--dsw-alias-border-l3': '#1a1c23',
    '--dsw-specific-sidebar-fill': '#1c1e26',
    '--dsw-alias-brand-primary': '#21bfc2',
    '--dsw-alias-mode-line-active': '#21bfc2',
  }),
  doomTheme('doom-ir-black', true, {
    '--dsw-alias-bg-base': '#000000',
    '--dsw-alias-bg-layer-1': '#121212',
    '--dsw-alias-bg-layer-2': '#3f444a',
    '--dsw-alias-bg-overlay': '#121212',
    '--dsw-alias-label-primary': '#f6f3e8',
    '--dsw-alias-label-secondary': '#5B6268',
    '--dsw-alias-border-l1': '#121212',
    '--dsw-alias-border-l2': '#202328',
    '--dsw-alias-border-l3': '#1c1f24',
    '--dsw-specific-sidebar-fill': '#121212',
    '--dsw-alias-brand-primary': '#96CBFE',
    '--dsw-alias-mode-line-active': '#96CBFE',
  }),
  doomTheme('doom-lantern', true, {
    '--dsw-alias-bg-base': '#261b17',
    '--dsw-alias-bg-layer-1': '#291812',
    '--dsw-alias-bg-layer-2': '#3F2F2A',
    '--dsw-alias-bg-overlay': '#291812',
    '--dsw-alias-label-primary': '#e4cbb3',
    '--dsw-alias-label-secondary': '#5B6268',
    '--dsw-alias-border-l1': '#291812',
    '--dsw-alias-border-l2': '#2D1F1A',
    '--dsw-alias-border-l3': '#1E1310',
    '--dsw-specific-sidebar-fill': '#291812',
    '--dsw-alias-brand-primary': '#66a4a4',
    '--dsw-alias-mode-line-active': '#66a4a4',
  }),
  doomTheme('doom-laserwave', true, {
    '--dsw-alias-bg-base': '#27212E',
    '--dsw-alias-bg-layer-1': '#1B1720',
    '--dsw-alias-bg-layer-2': '#4E415C',
    '--dsw-alias-bg-overlay': '#1B1720',
    '--dsw-alias-label-primary': '#FFFFFF',
    '--dsw-alias-label-secondary': '#EEEEEE',
    '--dsw-alias-border-l1': '#1B1720',
    '--dsw-alias-border-l2': '#282b33',
    '--dsw-alias-border-l3': '#24262D',
    '--dsw-specific-sidebar-fill': '#1B1720',
    '--dsw-alias-brand-primary': '#40B4C4',
    '--dsw-alias-mode-line-active': '#40B4C4',
  }),
  doomTheme('doom-material-dark', true, {
    '--dsw-alias-bg-base': '#212121',
    '--dsw-alias-bg-layer-1': '#3e3e3e',
    '--dsw-alias-bg-layer-2': '#4a4a4a',
    '--dsw-alias-bg-overlay': '#3e3e3e',
    '--dsw-alias-label-primary': '#EEFFFF',
    '--dsw-alias-label-secondary': '#BFC7D5',
    '--dsw-alias-border-l1': '#3e3e3e',
    '--dsw-alias-border-l2': '#303030',
    '--dsw-alias-border-l3': '#262626',
    '--dsw-specific-sidebar-fill': '#3e3e3e',
    '--dsw-alias-brand-primary': '#82aaff',
    '--dsw-alias-mode-line-active': '#82aaff',
  }),
  doomTheme('doom-material', true, {
    '--dsw-alias-bg-base': '#263238',
    '--dsw-alias-bg-layer-1': '#1C262B',
    '--dsw-alias-bg-layer-2': '#314048',
    '--dsw-alias-bg-overlay': '#1C262B',
    '--dsw-alias-label-primary': '#EEFFFF',
    '--dsw-alias-label-secondary': '#BFC7D5',
    '--dsw-alias-border-l1': '#1C262B',
    '--dsw-alias-border-l2': '#222D32',
    '--dsw-alias-border-l3': '#1C262B',
    '--dsw-specific-sidebar-fill': '#1C262B',
    '--dsw-alias-brand-primary': '#82aaff',
    '--dsw-alias-mode-line-active': '#82aaff',
  }),
  doomTheme('doom-miramare', true, {
    '--dsw-alias-bg-base': '#2a2426',
    '--dsw-alias-bg-layer-1': '#242021',
    '--dsw-alias-bg-layer-2': '#5b5b5b',
    '--dsw-alias-bg-overlay': '#242021',
    '--dsw-alias-label-primary': '#e6d6ac',
    '--dsw-alias-label-secondary': '#d8caac',
    '--dsw-alias-border-l1': '#242021',
    '--dsw-alias-border-l2': '#282828',
    '--dsw-alias-border-l3': '#1d2021',
    '--dsw-specific-sidebar-fill': '#242021',
    '--dsw-alias-brand-primary': '#89beba',
    '--dsw-alias-mode-line-active': '#89beba',
  }),
  doomTheme('doom-molokai', true, {
    '--dsw-alias-bg-base': '#1c1e1f',
    '--dsw-alias-bg-layer-1': '#222323',
    '--dsw-alias-bg-layer-2': '#4e4e4e',
    '--dsw-alias-bg-overlay': '#222323',
    '--dsw-alias-label-primary': '#d6d6d4',
    '--dsw-alias-label-secondary': '#556172',
    '--dsw-alias-border-l1': '#222323',
    '--dsw-alias-border-l2': '#1d1f20',
    '--dsw-alias-border-l3': '#151617',
    '--dsw-specific-sidebar-fill': '#222323',
    '--dsw-alias-brand-primary': '#268bd2',
    '--dsw-alias-mode-line-active': '#268bd2',
  }),
  doomTheme('doom-monokai-classic', true, {
    '--dsw-alias-bg-base': '#272822',
    '--dsw-alias-bg-layer-1': '#1D1E19',
    '--dsw-alias-bg-layer-2': '#4E4E4E',
    '--dsw-alias-bg-overlay': '#1D1E19',
    '--dsw-alias-label-primary': '#F8F8F2',
    '--dsw-alias-label-secondary': '#556172',
    '--dsw-alias-border-l1': '#1D1E19',
    '--dsw-alias-border-l2': '#1D1F20',
    '--dsw-alias-border-l3': '#161613',
    '--dsw-specific-sidebar-fill': '#1D1E19',
    '--dsw-alias-brand-primary': '#268bd2',
    '--dsw-alias-mode-line-active': '#268bd2',
  }),
  doomTheme('doom-monokai-machine', true, {
    '--dsw-alias-bg-base': '#273136',
    '--dsw-alias-bg-layer-1': '#1E2528',
    '--dsw-alias-bg-layer-2': '#545f62',
    '--dsw-alias-bg-overlay': '#1E2528',
    '--dsw-alias-label-primary': '#f2fffc',
    '--dsw-alias-label-secondary': '#c6c6c6',
    '--dsw-alias-border-l1': '#1E2528',
    '--dsw-alias-border-l2': '#2e363b',
    '--dsw-alias-border-l3': '#161b1e',
    '--dsw-specific-sidebar-fill': '#1E2528',
    '--dsw-alias-brand-primary': '#7cd5f1',
    '--dsw-alias-mode-line-active': '#7cd5f1',
  }),
  doomTheme('doom-monokai-octagon', true, {
    '--dsw-alias-bg-base': '#282a3a',
    '--dsw-alias-bg-layer-1': '#1E1F2B',
    '--dsw-alias-bg-layer-2': '#535763',
    '--dsw-alias-bg-overlay': '#1E1F2B',
    '--dsw-alias-label-primary': '#eaf2f1',
    '--dsw-alias-label-secondary': '#c6c6c6',
    '--dsw-alias-border-l1': '#1E1F2B',
    '--dsw-alias-border-l2': '#2e313d',
    '--dsw-alias-border-l3': '#161821',
    '--dsw-specific-sidebar-fill': '#1E1F2B',
    '--dsw-alias-brand-primary': '#9cd1bb',
    '--dsw-alias-mode-line-active': '#9cd1bb',
  }),
  doomTheme('doom-monokai-pro', true, {
    '--dsw-alias-bg-base': '#2D2A2E',
    '--dsw-alias-bg-layer-1': '#221F22',
    '--dsw-alias-bg-layer-2': '#383539',
    '--dsw-alias-bg-overlay': '#221F22',
    '--dsw-alias-label-primary': '#FCFCFA',
    '--dsw-alias-label-secondary': '#939293',
    '--dsw-alias-border-l1': '#221F22',
    '--dsw-alias-border-l2': '#212122',
    '--dsw-alias-border-l3': '#1B1B1B',
    '--dsw-specific-sidebar-fill': '#221F22',
    '--dsw-alias-brand-primary': '#78DCE8',
    '--dsw-alias-mode-line-active': '#78DCE8',
  }),
  doomTheme('doom-monokai-ristretto', true, {
    '--dsw-alias-bg-base': '#2c2525',
    '--dsw-alias-bg-layer-1': '#201C1C',
    '--dsw-alias-bg-layer-2': '#5b5353',
    '--dsw-alias-bg-overlay': '#201C1C',
    '--dsw-alias-label-primary': '#fff1f3',
    '--dsw-alias-label-secondary': '#c6c6c6',
    '--dsw-alias-border-l1': '#201C1C',
    '--dsw-alias-border-l2': '#332c2c',
    '--dsw-alias-border-l3': '#191515',
    '--dsw-specific-sidebar-fill': '#201C1C',
    '--dsw-alias-brand-primary': '#85dacc',
    '--dsw-alias-mode-line-active': '#85dacc',
  }),
  doomTheme('doom-monokai-spectrum', true, {
    '--dsw-alias-bg-base': '#222222',
    '--dsw-alias-bg-layer-1': '#191919',
    '--dsw-alias-bg-layer-2': '#525053',
    '--dsw-alias-bg-overlay': '#191919',
    '--dsw-alias-label-primary': '#f7f1ff',
    '--dsw-alias-label-secondary': '#c6c6c6',
    '--dsw-alias-border-l1': '#191919',
    '--dsw-alias-border-l2': '#2c2c2d',
    '--dsw-alias-border-l3': '#191919',
    '--dsw-specific-sidebar-fill': '#191919',
    '--dsw-alias-brand-primary': '#5ad4e6',
    '--dsw-alias-mode-line-active': '#5ad4e6',
  }),
  doomTheme('doom-moonlight', true, {
    '--dsw-alias-bg-base': '#212337',
    '--dsw-alias-bg-layer-1': '#191a2a',
    '--dsw-alias-bg-layer-2': '#2f334d',
    '--dsw-alias-bg-overlay': '#191a2a',
    '--dsw-alias-label-primary': '#c8d3f5',
    '--dsw-alias-label-secondary': '#b4c2f0',
    '--dsw-alias-border-l1': '#191a2a',
    '--dsw-alias-border-l2': '#1e2030',
    '--dsw-alias-border-l3': '#191a2a',
    '--dsw-specific-sidebar-fill': '#191a2a',
    '--dsw-alias-brand-primary': '#82aaff',
    '--dsw-alias-mode-line-active': '#82aaff',
  }),
  doomTheme('doom-nord-aurora', true, {
    '--dsw-alias-bg-base': '#2E3440',
    '--dsw-alias-bg-layer-1': '#272C36',
    '--dsw-alias-bg-layer-2': '#434C5E',
    '--dsw-alias-bg-overlay': '#272C36',
    '--dsw-alias-label-primary': '#ECEFF4',
    '--dsw-alias-label-secondary': '#E5E9F0',
    '--dsw-alias-border-l1': '#272C36',
    '--dsw-alias-border-l2': '#2C333F',
    '--dsw-alias-border-l3': '#242832',
    '--dsw-specific-sidebar-fill': '#272C36',
    '--dsw-alias-brand-primary': '#81A1C1',
    '--dsw-alias-mode-line-active': '#81A1C1',
  }),
  doomTheme('doom-nord-light', false, {
    '--dsw-alias-bg-base': '#E5E9F0',
    '--dsw-alias-bg-layer-1': '#D8DEE9',
    '--dsw-alias-bg-layer-2': '#B8C5DB',
    '--dsw-alias-bg-overlay': '#D8DEE9',
    '--dsw-alias-label-primary': '#3B4252',
    '--dsw-alias-label-secondary': '#2E3440',
    '--dsw-alias-border-l1': '#D8DEE9',
    '--dsw-alias-border-l2': '#D8DEE9',
    '--dsw-alias-border-l3': '#E3EAF5',
    '--dsw-specific-sidebar-fill': '#D8DEE9',
    '--dsw-alias-brand-primary': '#3B6EA8',
    '--dsw-alias-mode-line-active': '#3B6EA8',
  }),
  doomTheme('doom-nord', true, {
    '--dsw-alias-bg-base': '#2E3440',
    '--dsw-alias-bg-layer-1': '#272C36',
    '--dsw-alias-bg-layer-2': '#434C5E',
    '--dsw-alias-bg-overlay': '#272C36',
    '--dsw-alias-label-primary': '#ECEFF4',
    '--dsw-alias-label-secondary': '#E5E9F0',
    '--dsw-alias-border-l1': '#272C36',
    '--dsw-alias-border-l2': '#2C333F',
    '--dsw-alias-border-l3': '#242832',
    '--dsw-specific-sidebar-fill': '#272C36',
    '--dsw-alias-brand-primary': '#81A1C1',
    '--dsw-alias-mode-line-active': '#81A1C1',
  }),
  doomTheme('doom-nova', true, {
    '--dsw-alias-bg-base': '#3c4c55',
    '--dsw-alias-bg-layer-1': '#44545d',
    '--dsw-alias-bg-layer-2': '#3c4c55',
    '--dsw-alias-bg-overlay': '#44545d',
    '--dsw-alias-label-primary': '#c5d4dd',
    '--dsw-alias-label-secondary': '#c5c8c6',
    '--dsw-alias-border-l1': '#44545d',
    '--dsw-alias-border-l2': '#212122',
    '--dsw-alias-border-l3': '#1e272c',
    '--dsw-specific-sidebar-fill': '#44545d',
    '--dsw-alias-brand-primary': '#83AFE5',
    '--dsw-alias-mode-line-active': '#83AFE5',
  }),
  doomTheme('doom-oksolar-light', false, {
    '--dsw-alias-bg-base': '#FBF7EF',
    '--dsw-alias-bg-layer-1': '#F1E9D2',
    '--dsw-alias-bg-layer-2': '#8FAAAB',
    '--dsw-alias-bg-overlay': '#F1E9D2',
    '--dsw-alias-label-primary': '#657377',
    '--dsw-alias-label-secondary': '#5B7279',
    '--dsw-alias-border-l1': '#F1E9D2',
    '--dsw-alias-border-l2': '#8FAAAB',
    '--dsw-alias-border-l3': '#F1E9D2',
    '--dsw-specific-sidebar-fill': '#F1E9D2',
    '--dsw-alias-brand-primary': '#2B90D8',
    '--dsw-alias-mode-line-active': '#2B90D8',
  }),
  doomTheme('doom-old-hope', true, {
    '--dsw-alias-bg-base': '#1c1d20',
    '--dsw-alias-bg-layer-1': '#151619',
    '--dsw-alias-bg-layer-2': '#3f444a',
    '--dsw-alias-bg-overlay': '#151619',
    '--dsw-alias-label-primary': '#cbccd1',
    '--dsw-alias-label-secondary': '#5B6268',
    '--dsw-alias-border-l1': '#151619',
    '--dsw-alias-border-l2': '#202328',
    '--dsw-alias-border-l3': '#1c1f24',
    '--dsw-specific-sidebar-fill': '#151619',
    '--dsw-alias-brand-primary': '#4fb3d8',
    '--dsw-alias-mode-line-active': '#4fb3d8',
  }),
  doomTheme('doom-one-light', false, {
    '--dsw-alias-bg-base': '#fafafa',
    '--dsw-alias-bg-layer-1': '#f0f0f0',
    '--dsw-alias-bg-layer-2': '#9ca0a4',
    '--dsw-alias-bg-overlay': '#f0f0f0',
    '--dsw-alias-label-primary': '#383a42',
    '--dsw-alias-label-secondary': '#c6c7c7',
    '--dsw-alias-border-l1': '#f0f0f0',
    '--dsw-alias-border-l2': '#dfdfdf',
    '--dsw-alias-border-l3': '#e7e7e7',
    '--dsw-specific-sidebar-fill': '#f0f0f0',
    '--dsw-alias-brand-primary': '#4078f2',
    '--dsw-alias-mode-line-active': '#4078f2',
  }),
  doomTheme('doom-one', true, {
    '--dsw-alias-bg-base': '#282c34',
    '--dsw-alias-bg-layer-1': '#21242b',
    '--dsw-alias-bg-layer-2': '#3f444a',
    '--dsw-alias-bg-overlay': '#21242b',
    '--dsw-alias-label-primary': '#bbc2cf',
    '--dsw-alias-label-secondary': '#5B6268',
    '--dsw-alias-border-l1': '#21242b',
    '--dsw-alias-border-l2': '#202328',
    '--dsw-alias-border-l3': '#1c1f24',
    '--dsw-specific-sidebar-fill': '#21242b',
    '--dsw-alias-brand-primary': '#51afef',
    '--dsw-alias-mode-line-active': '#51afef',
  }),
  doomTheme('doom-opera-light', false, {
    '--dsw-alias-bg-base': '#fafafa',
    '--dsw-alias-bg-layer-1': '#eeeeee',
    '--dsw-alias-bg-layer-2': '#bdbdbd',
    '--dsw-alias-bg-overlay': '#eeeeee',
    '--dsw-alias-label-primary': '#2a2a2a',
    '--dsw-alias-label-secondary': '#454545',
    '--dsw-alias-border-l1': '#eeeeee',
    '--dsw-alias-border-l2': '#eeeeee',
    '--dsw-alias-border-l3': '#f5f5f5',
    '--dsw-specific-sidebar-fill': '#eeeeee',
    '--dsw-alias-brand-primary': '#3b6ea8',
    '--dsw-alias-mode-line-active': '#3b6ea8',
  }),
  doomTheme('doom-opera', true, {
    '--dsw-alias-bg-base': '#323334',
    '--dsw-alias-bg-layer-1': '#222224',
    '--dsw-alias-bg-layer-2': '#3f3f3f',
    '--dsw-alias-bg-overlay': '#222224',
    '--dsw-alias-label-primary': '#eceff4',
    '--dsw-alias-label-secondary': '#727269',
    '--dsw-alias-border-l1': '#222224',
    '--dsw-alias-border-l2': '#2e2e2e',
    '--dsw-alias-border-l3': '#1e1e1e',
    '--dsw-specific-sidebar-fill': '#222224',
    '--dsw-alias-brand-primary': '#80A0C2',
    '--dsw-alias-mode-line-active': '#80A0C2',
  }),
  doomTheme('doom-outrun-electric', true, {
    '--dsw-alias-bg-base': '#0c0a20',
    '--dsw-alias-bg-layer-1': '#090819',
    '--dsw-alias-bg-layer-2': '#2d2844',
    '--dsw-alias-bg-overlay': '#090819',
    '--dsw-alias-label-primary': '#f2f3f7',
    '--dsw-alias-label-secondary': '#7984D1',
    '--dsw-alias-border-l1': '#090819',
    '--dsw-alias-border-l2': '#110d26',
    '--dsw-alias-border-l3': '#1f1147',
    '--dsw-specific-sidebar-fill': '#090819',
    '--dsw-alias-brand-primary': '#1ea8fc',
    '--dsw-alias-mode-line-active': '#1ea8fc',
  }),
  doomTheme('doom-palenight', true, {
    '--dsw-alias-bg-base': '#292D3E',
    '--dsw-alias-bg-layer-1': '#242837',
    '--dsw-alias-bg-layer-2': '#4E5579',
    '--dsw-alias-bg-overlay': '#242837',
    '--dsw-alias-label-primary': '#EEFFFF',
    '--dsw-alias-label-secondary': '#BFC7D5',
    '--dsw-alias-border-l1': '#242837',
    '--dsw-alias-border-l2': '#232635',
    '--dsw-alias-border-l3': '#1e212e',
    '--dsw-specific-sidebar-fill': '#242837',
    '--dsw-alias-brand-primary': '#82aaff',
    '--dsw-alias-mode-line-active': '#82aaff',
  }),
  doomTheme('doom-peacock', true, {
    '--dsw-alias-bg-base': '#2b2a27',
    '--dsw-alias-bg-layer-1': '#1F1E1D',
    '--dsw-alias-bg-layer-2': '#3f444a',
    '--dsw-alias-bg-overlay': '#1F1E1D',
    '--dsw-alias-label-primary': '#ede0ce',
    '--dsw-alias-label-secondary': '#5B6268',
    '--dsw-alias-border-l1': '#1F1E1D',
    '--dsw-alias-border-l2': '#202328',
    '--dsw-alias-border-l3': '#1c1f24',
    '--dsw-specific-sidebar-fill': '#1F1E1D',
    '--dsw-alias-brand-primary': '#51afef',
    '--dsw-alias-mode-line-active': '#51afef',
  }),
  doomTheme('doom-pine', true, {
    '--dsw-alias-bg-base': '#0c1400',
    '--dsw-alias-bg-layer-1': '#121e00',
    '--dsw-alias-bg-layer-2': '#353e29',
    '--dsw-alias-bg-overlay': '#121e00',
    '--dsw-alias-label-primary': '#d5c9b0',
    '--dsw-alias-label-secondary': '#d5c4a1',
    '--dsw-alias-border-l1': '#121e00',
    '--dsw-alias-border-l2': '#0c1400',
    '--dsw-alias-border-l3': '#0c1400',
    '--dsw-specific-sidebar-fill': '#121e00',
    '--dsw-alias-brand-primary': '#8ec07c',
    '--dsw-alias-mode-line-active': '#8ec07c',
  }),
  doomTheme('doom-plain-dark', true, {
    '--dsw-alias-bg-base': '#222222',
    '--dsw-alias-bg-layer-1': '#222222',
    '--dsw-alias-bg-layer-2': '#202020',
    '--dsw-alias-bg-overlay': '#222222',
    '--dsw-alias-label-primary': '#d7d5d1',
    '--dsw-alias-label-secondary': '#e7e5e3',
    '--dsw-alias-border-l1': '#222222',
    '--dsw-alias-border-l2': '#bbbbbb',
    '--dsw-alias-border-l3': '#0e0c0a',
    '--dsw-specific-sidebar-fill': '#222222',
    '--dsw-alias-brand-primary': '#d7d5d1',
    '--dsw-alias-mode-line-active': '#d7d5d1',
  }),
  doomTheme('doom-plain', false, {
    '--dsw-alias-bg-base': '#ffffff',
    '--dsw-alias-bg-layer-1': '#f3f3f3',
    '--dsw-alias-bg-layer-2': '#e7e7e7',
    '--dsw-alias-bg-overlay': '#f3f3f3',
    '--dsw-alias-label-primary': '#282a2e',
    '--dsw-alias-label-secondary': '#c5c8c6',
    '--dsw-alias-border-l1': '#f3f3f3',
    '--dsw-alias-border-l2': '#444444',
    '--dsw-alias-border-l3': '#f1f3f5',
    '--dsw-specific-sidebar-fill': '#f3f3f3',
    '--dsw-alias-brand-primary': '#282a2e',
    '--dsw-alias-mode-line-active': '#282a2e',
  }),
  doomTheme('doom-rouge', true, {
    '--dsw-alias-bg-base': '#172030',
    '--dsw-alias-bg-layer-1': '#101828',
    '--dsw-alias-bg-layer-2': '#5D636E',
    '--dsw-alias-bg-overlay': '#101828',
    '--dsw-alias-label-primary': '#FAFFF6',
    '--dsw-alias-label-secondary': '#A7ACB9',
    '--dsw-alias-border-l1': '#101828',
    '--dsw-alias-border-l2': '#151D2B',
    '--dsw-alias-border-l3': '#0E131D',
    '--dsw-specific-sidebar-fill': '#101828',
    '--dsw-alias-brand-primary': '#6e94b9',
    '--dsw-alias-mode-line-active': '#6e94b9',
  }),
  doomTheme('doom-shades-of-purple', true, {
    '--dsw-alias-bg-base': '#2d2b55',
    '--dsw-alias-bg-layer-1': '#1e1e3f',
    '--dsw-alias-bg-layer-2': '#a599e9',
    '--dsw-alias-bg-overlay': '#1e1e3f',
    '--dsw-alias-label-primary': '#e3e9fa',
    '--dsw-alias-label-secondary': '#b4c2f0',
    '--dsw-alias-border-l1': '#1e1e3f',
    '--dsw-alias-border-l2': '#1e2030',
    '--dsw-alias-border-l3': '#191a2a',
    '--dsw-specific-sidebar-fill': '#1e1e3f',
    '--dsw-alias-brand-primary': '#82aaff',
    '--dsw-alias-mode-line-active': '#82aaff',
  }),
  doomTheme('doom-snazzy', true, {
    '--dsw-alias-bg-base': '#282a36',
    '--dsw-alias-bg-layer-1': '#242631',
    '--dsw-alias-bg-layer-2': '#a5a5a9',
    '--dsw-alias-bg-overlay': '#242631',
    '--dsw-alias-label-primary': '#f9f9f9',
    '--dsw-alias-label-secondary': '#d1d1d1',
    '--dsw-alias-border-l1': '#242631',
    '--dsw-alias-border-l2': '#43454f',
    '--dsw-alias-border-l3': '#34353e',
    '--dsw-specific-sidebar-fill': '#242631',
    '--dsw-alias-brand-primary': '#57c7ff',
    '--dsw-alias-mode-line-active': '#57c7ff',
  }),
  doomTheme('doom-solarized-dark-high-contrast', true, {
    '--dsw-alias-bg-base': '#002732',
    '--dsw-alias-bg-layer-1': '#00212B',
    '--dsw-alias-bg-layer-2': '#56697A',
    '--dsw-alias-bg-overlay': '#00212B',
    '--dsw-alias-label-primary': '#8d9fa1',
    '--dsw-alias-label-secondary': '#60767e',
    '--dsw-alias-border-l1': '#00212B',
    '--dsw-alias-border-l2': '#00212C',
    '--dsw-alias-border-l3': '#03282F',
    '--dsw-specific-sidebar-fill': '#00212B',
    '--dsw-alias-brand-primary': '#3c98e0',
    '--dsw-alias-mode-line-active': '#3c98e0',
  }),
  doomTheme('doom-solarized-light', false, {
    '--dsw-alias-bg-base': '#FDF6E3',
    '--dsw-alias-bg-layer-1': '#EEE8D5',
    '--dsw-alias-bg-layer-2': '#E1DBCD',
    '--dsw-alias-bg-overlay': '#EEE8D5',
    '--dsw-alias-label-primary': '#556b72',
    '--dsw-alias-label-secondary': '#7B8787',
    '--dsw-alias-border-l1': '#EEE8D5',
    '--dsw-alias-border-l2': '#FCF7E8',
    '--dsw-alias-border-l3': '#FCF8ED',
    '--dsw-specific-sidebar-fill': '#EEE8D5',
    '--dsw-alias-brand-primary': '#268bd2',
    '--dsw-alias-mode-line-active': '#268bd2',
  }),
  doomTheme('doom-sourcerer', true, {
    '--dsw-alias-bg-base': '#171717',
    '--dsw-alias-bg-layer-1': '#222222',
    '--dsw-alias-bg-layer-2': '#494952',
    '--dsw-alias-bg-overlay': '#222222',
    '--dsw-alias-label-primary': '#c2c2b0',
    '--dsw-alias-label-secondary': '#5D656B',
    '--dsw-alias-border-l1': '#222222',
    '--dsw-alias-border-l2': '#272727',
    '--dsw-alias-border-l3': '#1d2127',
    '--dsw-specific-sidebar-fill': '#222222',
    '--dsw-alias-brand-primary': '#87AFD7',
    '--dsw-alias-mode-line-active': '#87AFD7',
  }),
  doomTheme('doom-spacegrey', true, {
    '--dsw-alias-bg-base': '#2b303b',
    '--dsw-alias-bg-layer-1': '#232830',
    '--dsw-alias-bg-layer-2': '#4f5b66',
    '--dsw-alias-bg-overlay': '#232830',
    '--dsw-alias-label-primary': '#c0c5ce',
    '--dsw-alias-label-secondary': '#c0c5ce',
    '--dsw-alias-border-l1': '#232830',
    '--dsw-alias-border-l2': '#202328',
    '--dsw-alias-border-l3': '#1c1f24',
    '--dsw-specific-sidebar-fill': '#232830',
    '--dsw-alias-brand-primary': '#46D9FF',
    '--dsw-alias-mode-line-active': '#46D9FF',
  }),
  doomTheme('doom-tokyo-night', true, {
    '--dsw-alias-bg-base': '#1a1b26',
    '--dsw-alias-bg-layer-1': '#13141c',
    '--dsw-alias-bg-layer-2': '#8189af',
    '--dsw-alias-bg-overlay': '#13141c',
    '--dsw-alias-label-primary': '#a9b1d6',
    '--dsw-alias-label-secondary': '#c0caf5',
    '--dsw-alias-border-l1': '#13141c',
    '--dsw-alias-border-l2': '#61698b',
    '--dsw-alias-border-l3': '#51587a',
    '--dsw-specific-sidebar-fill': '#13141c',
    '--dsw-alias-brand-primary': '#7aa2f7',
    '--dsw-alias-mode-line-active': '#7aa2f7',
  }),
  doomTheme('doom-tomorrow-day', false, {
    '--dsw-alias-bg-base': '#ffffff',
    '--dsw-alias-bg-layer-1': '#f2f2f2',
    '--dsw-alias-bg-layer-2': '#C0bfbf',
    '--dsw-alias-bg-overlay': '#f2f2f2',
    '--dsw-alias-label-primary': '#4d4d4c',
    '--dsw-alias-label-secondary': '#a3a1a1',
    '--dsw-alias-border-l1': '#f2f2f2',
    '--dsw-alias-border-l2': '#dedede',
    '--dsw-alias-border-l3': '#e4e4e4',
    '--dsw-specific-sidebar-fill': '#f2f2f2',
    '--dsw-alias-brand-primary': '#4271ae',
    '--dsw-alias-mode-line-active': '#4271ae',
  }),
  doomTheme('doom-tomorrow-night', true, {
    '--dsw-alias-bg-base': '#1d1f21',
    '--dsw-alias-bg-layer-1': '#161719',
    '--dsw-alias-bg-layer-2': '#3f4040',
    '--dsw-alias-bg-overlay': '#161719',
    '--dsw-alias-label-primary': '#c5c8c6',
    '--dsw-alias-label-secondary': '#5c5e5e',
    '--dsw-alias-border-l1': '#161719',
    '--dsw-alias-border-l2': '#212122',
    '--dsw-alias-border-l3': '#1b1b1b',
    '--dsw-specific-sidebar-fill': '#161719',
    '--dsw-alias-brand-primary': '#81a2be',
    '--dsw-alias-mode-line-active': '#81a2be',
  }),
  doomTheme('doom-vibrant', true, {
    '--dsw-alias-bg-base': '#242730',
    '--dsw-alias-bg-layer-1': '#2a2e38',
    '--dsw-alias-bg-layer-2': '#484854',
    '--dsw-alias-bg-overlay': '#2a2e38',
    '--dsw-alias-label-primary': '#bbc2cf',
    '--dsw-alias-label-secondary': '#5D656B',
    '--dsw-alias-border-l1': '#2a2e38',
    '--dsw-alias-border-l2': '#21272d',
    '--dsw-alias-border-l3': '#1c1f24',
    '--dsw-specific-sidebar-fill': '#2a2e38',
    '--dsw-alias-brand-primary': '#51afef',
    '--dsw-alias-mode-line-active': '#51afef',
  }),
  doomTheme('doom-wilmersdorf', true, {
    '--dsw-alias-bg-base': '#282b33',
    '--dsw-alias-bg-layer-1': '#1f2024',
    '--dsw-alias-bg-layer-2': '#515462',
    '--dsw-alias-bg-overlay': '#1f2024',
    '--dsw-alias-label-primary': '#c6c6c6',
    '--dsw-alias-label-secondary': '#c9d9ff',
    '--dsw-alias-border-l1': '#1f2024',
    '--dsw-alias-border-l2': '#34373e',
    '--dsw-alias-border-l3': '#282b33',
    '--dsw-specific-sidebar-fill': '#1f2024',
    '--dsw-alias-brand-primary': '#819cd6',
    '--dsw-alias-mode-line-active': '#819cd6',
  }),
  doomTheme('doom-winter-is-coming-dark-blue', true, {
    '--dsw-alias-bg-base': '#011627',
    '--dsw-alias-bg-layer-1': '#062e5a',
    '--dsw-alias-bg-layer-2': '#5c7485',
    '--dsw-alias-bg-overlay': '#062e5a',
    '--dsw-alias-label-primary': '#a7dbf7',
    '--dsw-alias-label-secondary': '#7799bb',
    '--dsw-alias-border-l1': '#062e5a',
    '--dsw-alias-border-l2': '#2e3f4e',
    '--dsw-alias-border-l3': '#182735',
    '--dsw-specific-sidebar-fill': '#062e5a',
    '--dsw-alias-brand-primary': '#4373c2',
    '--dsw-alias-mode-line-active': '#4373c2',
  }),
  doomTheme('doom-winter-is-coming-light', false, {
    '--dsw-alias-bg-base': '#ffffff',
    '--dsw-alias-bg-layer-1': '#eff2ef',
    '--dsw-alias-bg-layer-2': '#8195b0',
    '--dsw-alias-bg-overlay': '#eff2ef',
    '--dsw-alias-label-primary': '#1857a4',
    '--dsw-alias-label-secondary': '#236ebf',
    '--dsw-alias-border-l1': '#eff2ef',
    '--dsw-alias-border-l2': '#bec9d7',
    '--dsw-alias-border-l3': '#dee4eb',
    '--dsw-specific-sidebar-fill': '#eff2ef',
    '--dsw-alias-brand-primary': '#2f86d2',
    '--dsw-alias-mode-line-active': '#2f86d2',
  }),
  doomTheme('doom-xcode', true, {
    '--dsw-alias-bg-base': '#292A30',
    '--dsw-alias-bg-layer-1': '#252629',
    '--dsw-alias-bg-layer-2': '#3f4040',
    '--dsw-alias-bg-overlay': '#252629',
    '--dsw-alias-label-primary': '#FFFFFF',
    '--dsw-alias-label-secondary': '#5c5e5e',
    '--dsw-alias-border-l1': '#252629',
    '--dsw-alias-border-l2': '#212122',
    '--dsw-alias-border-l3': '#1b1b1b',
    '--dsw-specific-sidebar-fill': '#252629',
    '--dsw-alias-brand-primary': '#5DD8FF',
    '--dsw-alias-mode-line-active': '#5DD8FF',
  }),
  doomTheme('doom-zenburn', true, {
    '--dsw-alias-bg-base': '#3F3F3F',
    '--dsw-alias-bg-layer-1': '#383838',
    '--dsw-alias-bg-layer-2': '#494949',
    '--dsw-alias-bg-overlay': '#383838',
    '--dsw-alias-label-primary': '#DCDCDC',
    '--dsw-alias-label-secondary': '#989890',
    '--dsw-alias-border-l1': '#383838',
    '--dsw-alias-border-l2': '#303030',
    '--dsw-alias-border-l3': '#2B2B2B',
    '--dsw-specific-sidebar-fill': '#383838',
    '--dsw-alias-brand-primary': '#8CD0D3',
    '--dsw-alias-mode-line-active': '#8CD0D3',
  }),
]
